# Generated by Django 4.0 on 2024-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0006_engine2'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '------'), (1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'GMC'), (6, 'Chrysler'), (7, 'Dodge'), (8, 'Jeep'), (9, 'Lincoln'), (10, 'Tesla')], null=True, verbose_name='Vehicle Make/Brand'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='make',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '------'), (1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'GMC'), (6, 'Chrysler'), (7, 'Dodge'), (8, 'Jeep'), (9, 'Lincoln'), (10, 'Tesla')], null=True, verbose_name='Make/Manufacturer'),
        ),
    ]
